var mill_data = [
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born",
            "1996": "Patrick was born"
        },
        "date_of_establishment": "1996",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "Extant",
        "lat": "Extant",
        "long": "17823",
        "name": "Barnacle Point",
        "parish": "St. George's"
    },
    {
        "additional_info": "THIS WAS CHANGED",
        "chronology": {
            "1994": "Murph was born",
            "1996": "Patrick was born"
        },
        "date_of_establishment": "1993",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "Extant",
        "lat": "17823",
        "long": "17823",
        "name": "Barnes Hill",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Blackman's",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "BlackmansMount Lucie",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Blackman's",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Carlisles",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Date Hill",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Donovans (Vaughans)",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Fitches Creek",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Giles Blizzard",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Gravenors",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Gunthorpes (ASF)",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Hight Point",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Judge Blizzards",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "LightfootsThe Grove",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Long Island",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Millars",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Nibbs",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "North Sound (Thomass HillCol. Thomas North Sound Plantation",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Paynters",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "SherwoodsLebanon",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Weirs (WaresGlanvillesLittle Zoar)",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Will Blizzards",
        "parish": "St. George's"
    },
    {
        "additional_info": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "chronology": {
            "1994": "Murph was born"
        },
        "date_of_establishment": "1996.33",
        "display_name": "Barnacle Point",
        "enslaved_peoples": "The sun was shining on the sea,\nShining with all his might:\nHe did his very best to make\nThe billows smooth and bright--\nAnd this was odd, because it was\nThe middle of the night.",
        "extant_or_ruin": "",
        "lat": "Extant",
        "long": "lalala",
        "name": "Winthorpes",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Allens Plantation (a.k.a. Mountains View)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Belle VueStony Hill Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "BelmontMurrays",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Belvedere Plantation (a.k.a. Hornes)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Bendals Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Body Ponds Plantation (a.k.a. Carleton)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Boones",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Brecknocks Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Briggins (Little Zoar)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Buckleys Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cassandra Gardens",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cedar Valley Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Clare Hall",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cooks",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Creek SideThibous Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Crosbies",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Denfields",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Drews Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Dunbars",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Five Islands Plantation (Upper and Lower Pelican)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Friars Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Galley Bay Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gambles",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "George Byams Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Golden Grove (Pauls)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "GraysTurnbils",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Hallidays Mountation (a.k.a. Gilleads, Gilliats, or Providence)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Harts and Royals",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Hawkebills Plantation (a.k.a. Hansons)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Herberts",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Hill HouseDry Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Hodges",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Langfords",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Marble Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "McKinnon",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mount Pleasant",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Olivers (Stock Estate)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Ottos",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Potters Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Renfrews",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Rose Hill and Hammersfield",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "St. ClareWilliams Plantation (Originally known as The Body)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "The Folly (Bath Lodge) Plantation (a.k.a. Duncombs Folly)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "The Union Plantation (HaddonHatton or Weekes)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "The Wood Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "ThibouJarvis Plantation (a.k.a. Mt. Joshua)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tomlinson",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Villa",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Weatherills",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Williams",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "YeptonsYapton Farm Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Barbuda",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Bettys Hope",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Big Duers",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Brookes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cedar Hill (Hall)",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cochrans",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cocoa Nut Hall & Hawes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cotton Garden",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cotton New Works",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Crabbs",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Freemans Upper",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gilberts",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Guiana Island",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Jonas",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Little Duers",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Lower Freemans",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "MartinsDiamond",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mercers Creek",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Pares",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Parham Hill & Parham Lodge",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Parham New Works",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Parrys",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "SandersonsOsbornes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Vernons (Wakering Hall)",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Yeamons",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Christian Hill  Cussacks",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Rooms",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Parsons Maul  Parson Maules",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Glanvilles",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Collins",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Grants",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Jefferson  Zion Hill",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mayers  Benlomand",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Retreat  Montgomery",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Comfort Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Grays Belfast  Lambert Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Wickhams  Upper Freemans",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Elliott  Frenchs",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Lon Lane",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gaynors",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "The Grange",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Elme Creek",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Goble  Gables",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Montpelie  Murrays",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Archbolds",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Brown Bay harmony Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Skerret & Folly  Nugents",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Colebrooks",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Walrond Upper",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Walrond Lower",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Frye  Frys",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Th Hope",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Harman  Harmons  Lloyds",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Lavingtons",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Lynchs",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Lyon (Upper & Lower)",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mannings",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Sheriff (Exchange)",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Watsons",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gree Island",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Harr Hardings",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Th Grange",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Matthews",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Burkes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Blakes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "L Roche",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Luca  Rock Hill",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Delaps",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Thomas",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cochran (Bethesda)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gale (Table Hill Gordon)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Morri Loobys",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Bodkins",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Willi Freemans",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tyrrel (Formerly Tankards or Orleans)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mill Byams (Folly  Byam)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Savannah",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Picadilly",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Richmonds",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Howards",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Horsefords",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Pattersons",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Swete (Sweets)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Buckshornes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Barter (Osbornes  Windward)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Doigs",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Dimsdal (Michaels Mount  Langhams)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Dee Bay  Dieppe Bay",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Fry Pasture",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Isaac Hill",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Guine Bush (Monks Hill)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cherr Hill (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Wind Hill (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tuck (Farley Bay miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Farley (Tucks miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Freeman Rest (Fig Tree Hill - miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Cabadg (Cabbage) Tree Plantation (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Barre Beef Estate (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Seaforths",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Smith (Darby)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Rigby (Perrys)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Gree Castle",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Monteros",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Ne Division (Tremills)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Hermitage",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Joll Hill",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Blubbe Valley (Rose Valley)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tranquil Vale",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tottenham Park",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Willocks",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Ffry (Frys)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Orang Valley (Furlongs)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Picart (Herman Vale)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Sawcolts",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Sag Hill (Tom Moores Mill  Upper)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Mil Hill",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Claremon (see #178)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Tremontain  The Mountain",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Youngs",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Young  Nantons",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Brook (Old Road)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Morris (Old Mill  Brambles)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Douglas Estate (Ravenscroft)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Yorke (Musketo Cove & Bear Gardens)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "lat": "",
        "long": "",
        "name": "Christia Valley  Biffins",
        "parish": "St. Mary's"
    }
]