var mill_data = [
    {
        "additional_info": "This mill was demolished when the Airport runway was lengthened, c. 1966 and there are no footprints left of this estate except for a burial ground belonging to the Nibbs family. \nAt the tip of Barnacle Point was Fort Byam which overlooked and protected Parham sound.  A map of Fort Byam surveyed by Kane William Horneck (1725) is located at John Carter Brown Library, which is at Brown University in Providence, Rhode Island, and includes an inventory of supplies, a profile of the hill the fort is on and reports of hurricane damage.   There is also a lovely water colour sketch of the Fort with a flag flying, in the collection of prints and artwork once belonging to Ben Quinn of Parham Hill. \n\nThe Nibb's Family Burial Ground was also situated at Barnacle Point with records available up to 1808.  Dr. Reg Murphy was called in when three headstones were disturbed by the backhoe in 2007, one Nibbs family member and a Mr. Collins and his daughter.  They were replaced and buried while the gravestones were packed and sent up to Betty’s Hope where they will be added to a collection of MI’s disturbed island wide by the ubiquitous backhoe in the name of development.    “Again, it's the first time I've ever seen someone buried with their name right on the coffin and it is done in brass text and the copper and it's because of that it survived and the fabric around it and the wood is nailed into survived so there's Jeremiah Nibbs [phonetic] and the date he died, born and died, perfectly preserved [inaudible].”   Dr. Reg Murphy\n\n1832: William Nibbs buried at “Barnacle Point.”\nInformation on the graves can be found in Oliver Vol.II .\n\n1801: Charles Curtis was manager for Samuel Martin at High Point around 1801-1812.   When Bertie Entwhistle died, Samuel Martin was his trustee and because of this connection, Charles Curtis also managed Golden Grove, Barnacle Point and Jolly Hill, estates belonging to Entwhistle. \n1822: Charles Curtis returned to England.  A relative of Curtis, Janet Richards, recently came into possession of a box of correspondence between him and Samuel Martin including 41 pages of Accounts of the Bertie Entwhistle Trust for the above estates from 1812-1822.Interesting little bits of information can be gleaned from these accounts to give an idea of what was happening on the estate during this period.\nBertie Entwistle who was a senior member of H.M. Council,died at sea on board R.M.S. “Seine” on his way back to Antigua at the ageof 69. It was said that he was worth £35,000 at the time of his death.Two letter books kept in the Jarvis family papers at the  University of Michigan can provide further information.\n\nIn 1829 this estate contained 64 acres and shared slaves with another estate.\n\nLegacies of British Slave-ownership:   www.ukl.ac.uk.lbs/search/\nAntigua 357 Barnacle Point was awarded £908, 14 s 6 d for slaves not recorded.\nRalph Peters was the single awardee.\n1851: Antigua Almanac shows Barnacle Point of 64 acres belonging to Heirs of Bertie Entwistle.   Include painting of Fort Byam at Barnacle Point – Jake Underhill of Parham Hill.\n\nwww.tombstones.bb  (2005)\nFound—headstones for Collins/William & Collins/Mary Hall.  Recorded not found Nibbs/Jeremiah.  Bird/Ann.\n\nFrancis Shand (1800-1868),absentee West Indian merchants and ship owners of Liverpool, who before his marriage, held several leases on local plantations. Through his marriage to Lydia Byam (1837) he became one of the largest proprietors of land in Antigua at that time. He had also been very active in negotiating the terms of emancipation in England.\nThe 1852 census listed among their properties: 517 acre plantation at Martin’s Byam or Fitche’s Creek in St George’s Parish, MountLucye - 230 acre estate also in St. George’s, Cedar Valley - 128 acre plantation in St. John’s parish, Harts & Royals - two estates consisting of 206 acres, the 90 acre Blizard estate and diverse other estates owned or leased by Francis Shand.  \nThe union produced 13 children except for that of their heir Charles Arthur Shand. By the mid 1980’s the only property left was Fiche’s Creek. Ghosts in a Plantation House. By Phylis Shand Allfrey\n\n1752: Map of Fort Byam – source Horneck, Kane Williams surveyor.\nA report of the state of the fortifications – battery called Byam Fort at the entrance to Parham Harbour. Includes an inventory ofsupplies, a profile of the hill the fort is on and reports of hurricane damage. Which is located at John Carter Brown Library, which is at Brown University in Providence, Rhode Island.\n“The condition of Fort Byam. The flag staff blown down, the Guard House much hurt and ------- thrown down by the late hurricane.”\n\nR. Allen Stanford who also owns Maiden Island owned Barnacle Point, the land on the sea north and east of the airport. He has built a business jet aircraft maintenance facility, restaurant and docking area. In 2010, Mr. Stanford was jailed in Texas, U.S.A,for his offshore and banking ponzi schemes leaving many people bankrupt, many employees without a job and his properties being contested.  All of his holdings in Antigua were placed in receivership.\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "chronology": {
            "1790": " Jeremiah Nibbs.               Bapt. 1728      1877/78 Luffman map",
            "1798": " Bertie Entwhistle             d.1803  ",
            "1829": " Bertie Entwhistle             Leased to Shand & Co.   ",
            "1843": " Heirs of Bertie Entwhistle   ",
            "1868": " Francis Shand                 b.1800  d.1868",
            "1878": " Heirs of Francis Shand        1872",
            "1933": " Mrs. M.T. Camacho             1933",
            "1940": " Leased to the U.S. Forces.  ",
            "1966": " Coolidge Airport extended (Later renamed The V.C.  Bird Intl. Airport).",
            "1968": " Antigua Government – Crown Land  ",
            "2003": " R. Allen Stanford – area surrounding airport.  b.1950"
        },
        "date_of_establishment": "1750",
        "display_name": "Barnacle Point\t\n\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "enslaved_peoples": "Based on contemporary research, we have little information to share about the enslaved peoples from this plantation at this time.  However, we will continue our quest for more information about these vital individuals.\n\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "extant_or_ruin": "Ruin",
        "image": "Mill_Files/Photos/Barnacle Point.jpeg",
        "lat": "-61.778625",
        "long": "17.139147",
        "name": "Barnacle Point",
        "parish": "St. George's"
    },
    {
        "additional_info": "There is no longer a mill at this site and very little remains to identify this estate.   Old timers say that it was located at the extreme western end of Powell’s road and that it was destroyed when runway #10 was built to accommodate low flying aircraft. Remains of a few old small stone buildings covered in wild coralita, can still be seen in the back of the village at the top of the hill.    As with most of the estates, the crest of the hill or high point was always built on in order to catch the breeze for the windmills and the cooling effect.  It also allowed the planter to survey most of the estate. This now gives the village of Barnes Hill magnificent views towards the north of the island towards the sea.\n\n1678: Maj. William Barnes, Speaker of Assembly\n1679: John Richardson granted 100 acres by Jeremiah Watkins.\n1680: Maj. William Barnes has a patent for 237 acres - late of Mr. Wlm. Yeamons   \n1681: Maj. William Barnes has a patent for 230 acres granted by Wlm. Stapleton  \nAntigua Film Project possess a letter written about my aunt, Mrs. Ann Barnes.   “I very well remember her husband Mr. William Barnes, when I was a child in Antigua and that she was his second wife is very certain for I well know Mr. John Barnes now in New England who was a son of said William Barnes, deceased, and have heard of another soan at Bristol, a soap boiler, but my Aunt Barnes had no child of her own alive.” \n1695: Maj. William Barnes died in 1695 and was buried in St. George’s Churchyard. He was the first settler to be buried within the sanctuary of a place of worship.\nWill proved in 1695.   \n1696: Anne Barnes rated on 500 acres in St. Mary’s Vestry book.    \n1705: Will of John Richardson of Parham.   “.... to my son John Richardson all my estate.... £15 to be laid out to wall in a burial place on my plantation 50’ square.”\n1718: “To my wife Ann Thomas £500 & £400/year so long as she remains my widow, only £100/year if she marry, also all plate, household goods, chariot and horses.   If she resides in Antigua I give her the use of 100 acres called “Barnes” adj. to Mr. Francis Carlisle.”   Vere Oliver Vol.III p.128\n1719: John Barnes sold his estate by Act; in 1727 of New England.    Vere Oliver Vol.I P.34/35 \n1734: “John Richardson of “Barnes” in North Sound, only son and heir, died 1734.”   Vere Oliver Vol.III p.46\n1792: Elizabeth Richardson of St. Martin, widow of John Richardson of Antigua and late of St. Martin. “Doctor of Physick deceased,” releases her dower claims to Samuel Martin, Collector of Customs for the Port of Saint John’s, Antigua, and Thomas Jarvis and Daniel Hill of Antigua.   The Beinecke Collection, Hamilton College.\n1827: Letter from John Jarvis to GRP Jarvis dated 16 September, 1827.   “He will send his two sons to his brother.  Damage by gales in Antigua.”   Ref. Jarvis/5/A/7/54\nLetters and personal correspondence held by the Lincolnshire Archives Ref: Jarvis V/A/9?41\nJohn S. Jarvis and his wife paid L190 to manumit George Marshall on September 6th, 1823.   Manumission (Antigua) 1821-1825.\n\nIn the slave registry 1813-1834 for John S. Jarvis, lists James Barrett, Fredericka Theresa, George Humphry, Lettice, John Prince, William Henry all between 1mth and 4 years old.\n\n1842: West Indian Encumbered Estates Court re Francis Wightwick Esq. to Geor. Savage Martin and William Henry Martin Esq. re: conveyance of the Nibbs and High Point Plantations in Antigua.   Francis Wightwick (Surrey), Winifred Wightwick (Surrey spinster) George Savage and William Henry Martin (Antigua); Nibbs of Popeshead, High Point, Barnes Hill and Ronans plantations, united and called High Point Plantation.    M569 The Beinecke Collection, Hamilton College.\n1871: A scene of the event is pictured in Christian Work, Nov. 1st 1871 – Mission Field.   “The Bishop of Antigua states that “Every estate in my parish has suffered badly and every chimney is thrown down.   On the day after the hurricane I buried eleven persons killed and on the next two days three who died from injuries sustained.   On Monday night, over 300 persons sat up together in the open air, exposed to incessant and drenching rains in St. Mark’s village, and the same scene was enacted in Barnes Hill distributed with my own hands every day 320 small loaves and 100 pieces of salt fish and sickness is now, alas beginning to abound.   Barnes Hill School Chapel with brand new benches and lamps is utterly destroyed and blown to the winds   The whole village (700 inhabitants) is in complete ruins.”\n\nDr. John Freeland wrote “Notes on Leprosy as Observed in Antigua, West Indies.” Based on his experience working with lepers for over 30 years.  It appeared in the British Medical Journal Oct 5th, 1889.   He was the Government Medical Officer at the time.   He came to the conclusion that it must depend upon “some very special kind of poison of rare occurrence taken in connection with food.”   He goes on to say, “The chief food of the negroes and lower orders here has been for generations past a salted fish called cod, but it might be anything else.   It is imported from the United States of America.   As health officer I can truly say that it does not always arrive or keep her perfectly sweet, nor did the effluvium from this food ever remind me very forcibly of the hay-fields of England.”\nIn 1890, Dr. John Freeland estimated there were then 53 lepers in Antigua, twelve men and 19 women who resided in the leper colony.  Dr. Freeland md. Miss Eleanor Foote October 30, 1819.\nAn interesting note is Freida Cassin’s “With Silent Tread” thought to be the earliest novel of Antigua and Barbuda in 1890.   It is a novel involving leprosy.   Cassin was an Antiguan creole who also founded in 1895 a literary journal the “Carib” that ran to six issues.\n\n1943: August 1st The Gunthorpes Estates, Ltd. was restructured (see #64 Gunthorpe’s) into a ‘new’ company renamed Antigua Syndicate Estates, Ltd.   Negotiations with Mary Camacho in 1947 for Carlisle and part of Barnes Hill fell through.   However, in 1949 in order to facilitate transfer of the estate including Carlisle’s, to the Syndicate Estates there was considerable encroachment which had to be recognized   The transfer took place on 25th February, 1949 for $2,500 according to the minutes of the ASE.\n\n1969:  The Lands of Antigua & Barbuda Sugar Factory, Limited and The Antigua & Barbuda Syndicate Estates Limited (Vesting) Act.   30th December, 1969.\n24.All that piece or parcel of land forming part of Barnes Hill, approximately 27.21 acres as contained in certificate of Title No.251949 dated 20th August, 1949 and registered in Register Book S Folio 19.\n\nTaken from the History of Barnes Hill.\nThe village, it is recorded, was named in honor of a young English settler, William Barnes, who was born in December 1656 and died in November 1695 who has the distinction of being the first known settler to be buried in a place of worship, the St. George’s Anglican Church, in Fitches Creek.\nThe Barnes Hill community had one of the earlier police stations and there was a solid sugar mill near the extreme western end of the Powell’s road.   This mill was destroyed to accommodate aircraft flying almost directly over the area on approach to Runway 10.   The community was also home to two of the three important lime kilns in the country.   The projects produced white lime used in construction and in controlling human waste.   White lime was also used for painting walls and for many years. To mark the creases for cricket matches and play boundaries in football.\nBarnes Hill also produced only the fourth steel band to be established in Antigua and Barbuda when Sun Valley was established in 1949 following Hell’s Gate, Brute Force and Red Army.   It was splinters from the feared “country band” that formed North Stars of New Winthorpes and Rising Sun of Pigotts – the likes of Manning and Vincent Freeland will attest to that fact.   Two top players at one time were referred to as “Bum.”\n“Bum” Jardine of Brute Force and Roy “Bum/Bumpers” Solomon of Barnes Hill.\n\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "chronology": {
            "1695-1719": " Sold by John Barnes",
            "1705": " John Richardson (d.1734)",
            "1719": " John Richardson (w.1705)",
            "1823": " John S. Jarvis (c.1827-c.1898)   "
        },
        "date_of_establishment": "1680",
        "display_name": "Barnes Hill\n\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "enslaved_peoples": "Based on contemporary research, we have little information to share about the enslaved peoples from this plantation at this time. We only know that the slave registry from 1813-1834 only lists “James Barrett, Fredericka Theresa, George Humphry, Lettice, John Prince, William Henry all between 1mth and 4 years old.” We will continue our quest for more information about these vital individuals.\n\n\n\n\n\n\n\n\n<<<<<<< HEAD\n\n\n=======\n>>>>>>> d768156c536e76b05ded1a5495e7f7cf0b25d06d",
        "extant_or_ruin": "Ruin",
        "image": "Mill_Files/Photos/Barnes Hill.jpeg",
        "lat": "-61.801928",
        "long": "17.142879",
        "name": "Barnes Hill",
        "parish": "St. George's"
    },
    {
        "additional_info": "\nwell lets see about that",
        "chronology": {
            "1963": " Damn yeah it works",
            "1994": " Does it work?"
        },
        "date_of_establishment": "1963",
        "display_name": "Barnacle Point\t",
        "enslaved_peoples": "\nOh wow",
        "extant_or_ruin": "\nExtant",
        "image": "Mill_Files/Photos/BlackmansMount Lucie.jpeg",
        "lat": "1232",
        "long": "1234",
        "name": "BlackmansMount Lucie",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Carlisles.jpeg",
        "lat": "",
        "long": "",
        "name": "Carlisles",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Date Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Date Hill",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Donovans (Vaughans).jpeg",
        "lat": "",
        "long": "",
        "name": "Donovans (Vaughans)",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Fitches Creek.jpeg",
        "lat": "",
        "long": "",
        "name": "Fitches Creek",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Giles Blizzard.jpeg",
        "lat": "",
        "long": "",
        "name": "Giles Blizzard",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gravenors.jpeg",
        "lat": "",
        "long": "",
        "name": "Gravenors",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gunthorpes (ASF).jpeg",
        "lat": "",
        "long": "",
        "name": "Gunthorpes (ASF)",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hight Point.jpeg",
        "lat": "",
        "long": "",
        "name": "Hight Point",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Judge Blizzards.jpeg",
        "lat": "",
        "long": "",
        "name": "Judge Blizzards",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/LightfootsThe Grove.jpeg",
        "lat": "",
        "long": "",
        "name": "LightfootsThe Grove",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Long Island.jpeg",
        "lat": "",
        "long": "",
        "name": "Long Island",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Millars.jpeg",
        "lat": "",
        "long": "",
        "name": "Millars",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Nibbs.jpeg",
        "lat": "",
        "long": "",
        "name": "Nibbs",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/North Sound (Thomass HillCol. Thomas North Sound Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "North Sound (Thomass HillCol. Thomas North Sound Plantation",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Paynters.jpeg",
        "lat": "",
        "long": "",
        "name": "Paynters",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/SherwoodsLebanon.jpeg",
        "lat": "",
        "long": "",
        "name": "SherwoodsLebanon",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Weirs (WaresGlanvillesLittle Zoar).jpeg",
        "lat": "",
        "long": "",
        "name": "Weirs (WaresGlanvillesLittle Zoar)",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Will Blizzards.jpeg",
        "lat": "",
        "long": "",
        "name": "Will Blizzards",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Winthorpes.jpeg",
        "lat": "",
        "long": "",
        "name": "Winthorpes",
        "parish": "St. George's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Allens Plantation (a.k.a. Mountains View).jpeg",
        "lat": "",
        "long": "",
        "name": "Allens Plantation (a.k.a. Mountains View)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Belle VueStony Hill Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Belle VueStony Hill Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/BelmontMurrays.jpeg",
        "lat": "",
        "long": "",
        "name": "BelmontMurrays",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Belvedere Plantation (a.k.a. Hornes).jpeg",
        "lat": "",
        "long": "",
        "name": "Belvedere Plantation (a.k.a. Hornes)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Bendals Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Bendals Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Body Ponds Plantation (a.k.a. Carleton).jpeg",
        "lat": "",
        "long": "",
        "name": "Body Ponds Plantation (a.k.a. Carleton)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Boones.jpeg",
        "lat": "",
        "long": "",
        "name": "Boones",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Brecknocks Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Brecknocks Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Briggins (Little Zoar).jpeg",
        "lat": "",
        "long": "",
        "name": "Briggins (Little Zoar)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Buckleys Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Buckleys Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cassandra Gardens.jpeg",
        "lat": "",
        "long": "",
        "name": "Cassandra Gardens",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cedar Valley Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Cedar Valley Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Clare Hall.jpeg",
        "lat": "",
        "long": "",
        "name": "Clare Hall",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cooks.jpeg",
        "lat": "",
        "long": "",
        "name": "Cooks",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Creek SideThibous Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Creek SideThibous Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Crosbies.jpeg",
        "lat": "",
        "long": "",
        "name": "Crosbies",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Denfields.jpeg",
        "lat": "",
        "long": "",
        "name": "Denfields",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Drews Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Drews Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Dunbars.jpeg",
        "lat": "",
        "long": "",
        "name": "Dunbars",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Five Islands Plantation (Upper and Lower Pelican).jpeg",
        "lat": "",
        "long": "",
        "name": "Five Islands Plantation (Upper and Lower Pelican)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Friars Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Friars Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Galley Bay Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Galley Bay Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gambles.jpeg",
        "lat": "",
        "long": "",
        "name": "Gambles",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/George Byams Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "George Byams Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Golden Grove (Pauls).jpeg",
        "lat": "",
        "long": "",
        "name": "Golden Grove (Pauls)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/GraysTurnbils.jpeg",
        "lat": "",
        "long": "",
        "name": "GraysTurnbils",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hallidays Mountation (a.k.a. Gilleads, Gilliats, or Providence).jpeg",
        "lat": "",
        "long": "",
        "name": "Hallidays Mountation (a.k.a. Gilleads, Gilliats, or Providence)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Harts and Royals.jpeg",
        "lat": "",
        "long": "",
        "name": "Harts and Royals",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hawkebills Plantation (a.k.a. Hansons).jpeg",
        "lat": "",
        "long": "",
        "name": "Hawkebills Plantation (a.k.a. Hansons)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Herberts.jpeg",
        "lat": "",
        "long": "",
        "name": "Herberts",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hill HouseDry Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Hill HouseDry Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hodges.jpeg",
        "lat": "",
        "long": "",
        "name": "Hodges",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Langfords.jpeg",
        "lat": "",
        "long": "",
        "name": "Langfords",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Marble Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Marble Hill",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/McKinnon.jpeg",
        "lat": "",
        "long": "",
        "name": "McKinnon",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mount Pleasant.jpeg",
        "lat": "",
        "long": "",
        "name": "Mount Pleasant",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Olivers (Stock Estate).jpeg",
        "lat": "",
        "long": "",
        "name": "Olivers (Stock Estate)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Ottos.jpeg",
        "lat": "",
        "long": "",
        "name": "Ottos",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Potters Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "Potters Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Renfrews.jpeg",
        "lat": "",
        "long": "",
        "name": "Renfrews",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Rose Hill and Hammersfield.jpeg",
        "lat": "",
        "long": "",
        "name": "Rose Hill and Hammersfield",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/St. ClareWilliams Plantation (Originally known as The Body).jpeg",
        "lat": "",
        "long": "",
        "name": "St. ClareWilliams Plantation (Originally known as The Body)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/The Folly (Bath Lodge) Plantation (a.k.a. Duncombs Folly).jpeg",
        "lat": "",
        "long": "",
        "name": "The Folly (Bath Lodge) Plantation (a.k.a. Duncombs Folly)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/The Union Plantation (HaddonHatton or Weekes).jpeg",
        "lat": "",
        "long": "",
        "name": "The Union Plantation (HaddonHatton or Weekes)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/The Wood Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "The Wood Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/ThibouJarvis Plantation (a.k.a. Mt. Joshua).jpeg",
        "lat": "",
        "long": "",
        "name": "ThibouJarvis Plantation (a.k.a. Mt. Joshua)",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tomlinson.jpeg",
        "lat": "",
        "long": "",
        "name": "Tomlinson",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Villa.jpeg",
        "lat": "",
        "long": "",
        "name": "Villa",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Weatherills.jpeg",
        "lat": "",
        "long": "",
        "name": "Weatherills",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Williams.jpeg",
        "lat": "",
        "long": "",
        "name": "Williams",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/YeptonsYapton Farm Plantation.jpeg",
        "lat": "",
        "long": "",
        "name": "YeptonsYapton Farm Plantation",
        "parish": "St. John's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Barbuda.jpeg",
        "lat": "",
        "long": "",
        "name": "Barbuda",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Bettys Hope.jpeg",
        "lat": "",
        "long": "",
        "name": "Bettys Hope",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Big Duers.jpeg",
        "lat": "",
        "long": "",
        "name": "Big Duers",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Brookes.jpeg",
        "lat": "",
        "long": "",
        "name": "Brookes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cedar Hill (Hall).jpeg",
        "lat": "",
        "long": "",
        "name": "Cedar Hill (Hall)",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cochrans.jpeg",
        "lat": "",
        "long": "",
        "name": "Cochrans",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cocoa Nut Hall & Hawes.jpeg",
        "lat": "",
        "long": "",
        "name": "Cocoa Nut Hall & Hawes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cotton Garden.jpeg",
        "lat": "",
        "long": "",
        "name": "Cotton Garden",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cotton New Works.jpeg",
        "lat": "",
        "long": "",
        "name": "Cotton New Works",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Crabbs.jpeg",
        "lat": "",
        "long": "",
        "name": "Crabbs",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Freemans Upper.jpeg",
        "lat": "",
        "long": "",
        "name": "Freemans Upper",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gilberts.jpeg",
        "lat": "",
        "long": "",
        "name": "Gilberts",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Guiana Island.jpeg",
        "lat": "",
        "long": "",
        "name": "Guiana Island",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Jonas.jpeg",
        "lat": "",
        "long": "",
        "name": "Jonas",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Little Duers.jpeg",
        "lat": "",
        "long": "",
        "name": "Little Duers",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Lower Freemans.jpeg",
        "lat": "",
        "long": "",
        "name": "Lower Freemans",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/MartinsDiamond.jpeg",
        "lat": "",
        "long": "",
        "name": "MartinsDiamond",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mercers Creek.jpeg",
        "lat": "",
        "long": "",
        "name": "Mercers Creek",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Pares.jpeg",
        "lat": "",
        "long": "",
        "name": "Pares",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Parham Hill & Parham Lodge.jpeg",
        "lat": "",
        "long": "",
        "name": "Parham Hill & Parham Lodge",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Parham New Works.jpeg",
        "lat": "",
        "long": "",
        "name": "Parham New Works",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Parrys.jpeg",
        "lat": "",
        "long": "",
        "name": "Parrys",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/SandersonsOsbornes.jpeg",
        "lat": "",
        "long": "",
        "name": "SandersonsOsbornes",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Vernons (Wakering Hall).jpeg",
        "lat": "",
        "long": "",
        "name": "Vernons (Wakering Hall)",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Yeamons.jpeg",
        "lat": "",
        "long": "",
        "name": "Yeamons",
        "parish": "St. Peter's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Christian Hill  Cussacks.jpeg",
        "lat": "",
        "long": "",
        "name": "Christian Hill  Cussacks",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Rooms.jpeg",
        "lat": "",
        "long": "",
        "name": "Rooms",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Parsons Maul  Parson Maules.jpeg",
        "lat": "",
        "long": "",
        "name": "Parsons Maul  Parson Maules",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Glanvilles.jpeg",
        "lat": "",
        "long": "",
        "name": "Glanvilles",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Collins.jpeg",
        "lat": "",
        "long": "",
        "name": "Collins",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Grants.jpeg",
        "lat": "",
        "long": "",
        "name": "Grants",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Jefferson  Zion Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Jefferson  Zion Hill",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mayers  Benlomand.jpeg",
        "lat": "",
        "long": "",
        "name": "Mayers  Benlomand",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Retreat  Montgomery.jpeg",
        "lat": "",
        "long": "",
        "name": "Retreat  Montgomery",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Comfort Hall.jpeg",
        "lat": "",
        "long": "",
        "name": "Comfort Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Grays Belfast  Lambert Hall.jpeg",
        "lat": "",
        "long": "",
        "name": "Grays Belfast  Lambert Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Wickhams  Upper Freemans.jpeg",
        "lat": "",
        "long": "",
        "name": "Wickhams  Upper Freemans",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Elliott  Frenchs.jpeg",
        "lat": "",
        "long": "",
        "name": "Elliott  Frenchs",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Lon Lane.jpeg",
        "lat": "",
        "long": "",
        "name": "Lon Lane",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gaynors.jpeg",
        "lat": "",
        "long": "",
        "name": "Gaynors",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/The Grange.jpeg",
        "lat": "",
        "long": "",
        "name": "The Grange",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Elme Creek.jpeg",
        "lat": "",
        "long": "",
        "name": "Elme Creek",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Goble  Gables.jpeg",
        "lat": "",
        "long": "",
        "name": "Goble  Gables",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Montpelie  Murrays.jpeg",
        "lat": "",
        "long": "",
        "name": "Montpelie  Murrays",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Archbolds.jpeg",
        "lat": "",
        "long": "",
        "name": "Archbolds",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Brown Bay harmony Hall.jpeg",
        "lat": "",
        "long": "",
        "name": "Brown Bay harmony Hall",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Skerret & Folly  Nugents.jpeg",
        "lat": "",
        "long": "",
        "name": "Skerret & Folly  Nugents",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Colebrooks.jpeg",
        "lat": "",
        "long": "",
        "name": "Colebrooks",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Walrond Upper.jpeg",
        "lat": "",
        "long": "",
        "name": "Walrond Upper",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Walrond Lower.jpeg",
        "lat": "",
        "long": "",
        "name": "Walrond Lower",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Frye  Frys.jpeg",
        "lat": "",
        "long": "",
        "name": "Frye  Frys",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Th Hope.jpeg",
        "lat": "",
        "long": "",
        "name": "Th Hope",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Harman  Harmons  Lloyds.jpeg",
        "lat": "",
        "long": "",
        "name": "Harman  Harmons  Lloyds",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Lavingtons.jpeg",
        "lat": "",
        "long": "",
        "name": "Lavingtons",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Lynchs.jpeg",
        "lat": "",
        "long": "",
        "name": "Lynchs",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Lyon (Upper & Lower).jpeg",
        "lat": "",
        "long": "",
        "name": "Lyon (Upper & Lower)",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mannings.jpeg",
        "lat": "",
        "long": "",
        "name": "Mannings",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Sheriff (Exchange).jpeg",
        "lat": "",
        "long": "",
        "name": "Sheriff (Exchange)",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Watsons.jpeg",
        "lat": "",
        "long": "",
        "name": "Watsons",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gree Island.jpeg",
        "lat": "",
        "long": "",
        "name": "Gree Island",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Harr Hardings.jpeg",
        "lat": "",
        "long": "",
        "name": "Harr Hardings",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Th Grange.jpeg",
        "lat": "",
        "long": "",
        "name": "Th Grange",
        "parish": "St. Philip's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Matthews.jpeg",
        "lat": "",
        "long": "",
        "name": "Matthews",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Burkes.jpeg",
        "lat": "",
        "long": "",
        "name": "Burkes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Blakes.jpeg",
        "lat": "",
        "long": "",
        "name": "Blakes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/L Roche.jpeg",
        "lat": "",
        "long": "",
        "name": "L Roche",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Luca  Rock Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Luca  Rock Hill",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Delaps.jpeg",
        "lat": "",
        "long": "",
        "name": "Delaps",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Thomas.jpeg",
        "lat": "",
        "long": "",
        "name": "Thomas",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cochran (Bethesda).jpeg",
        "lat": "",
        "long": "",
        "name": "Cochran (Bethesda)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gale (Table Hill Gordon).jpeg",
        "lat": "",
        "long": "",
        "name": "Gale (Table Hill Gordon)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Morri Loobys.jpeg",
        "lat": "",
        "long": "",
        "name": "Morri Loobys",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Bodkins.jpeg",
        "lat": "",
        "long": "",
        "name": "Bodkins",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Willi Freemans.jpeg",
        "lat": "",
        "long": "",
        "name": "Willi Freemans",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tyrrel (Formerly Tankards or Orleans).jpeg",
        "lat": "",
        "long": "",
        "name": "Tyrrel (Formerly Tankards or Orleans)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mill Byams (Folly  Byam).jpeg",
        "lat": "",
        "long": "",
        "name": "Mill Byams (Folly  Byam)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Savannah.jpeg",
        "lat": "",
        "long": "",
        "name": "Savannah",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Picadilly.jpeg",
        "lat": "",
        "long": "",
        "name": "Picadilly",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Richmonds.jpeg",
        "lat": "",
        "long": "",
        "name": "Richmonds",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Howards.jpeg",
        "lat": "",
        "long": "",
        "name": "Howards",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Horsefords.jpeg",
        "lat": "",
        "long": "",
        "name": "Horsefords",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Pattersons.jpeg",
        "lat": "",
        "long": "",
        "name": "Pattersons",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Swete (Sweets).jpeg",
        "lat": "",
        "long": "",
        "name": "Swete (Sweets)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Buckshornes.jpeg",
        "lat": "",
        "long": "",
        "name": "Buckshornes",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Barter (Osbornes  Windward).jpeg",
        "lat": "",
        "long": "",
        "name": "Barter (Osbornes  Windward)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Doigs.jpeg",
        "lat": "",
        "long": "",
        "name": "Doigs",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Dimsdal (Michaels Mount  Langhams).jpeg",
        "lat": "",
        "long": "",
        "name": "Dimsdal (Michaels Mount  Langhams)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Dee Bay  Dieppe Bay.jpeg",
        "lat": "",
        "long": "",
        "name": "Dee Bay  Dieppe Bay",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Fry Pasture.jpeg",
        "lat": "",
        "long": "",
        "name": "Fry Pasture",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Isaac Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Isaac Hill",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Guine Bush (Monks Hill).jpeg",
        "lat": "",
        "long": "",
        "name": "Guine Bush (Monks Hill)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cherr Hill (miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Cherr Hill (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Wind Hill (miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Wind Hill (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tuck (Farley Bay miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Tuck (Farley Bay miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Farley (Tucks miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Farley (Tucks miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Freeman Rest (Fig Tree Hill - miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Freeman Rest (Fig Tree Hill - miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Cabadg (Cabbage) Tree Plantation (miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Cabadg (Cabbage) Tree Plantation (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Barre Beef Estate (miscellaneous).jpeg",
        "lat": "",
        "long": "",
        "name": "Barre Beef Estate (miscellaneous)",
        "parish": "St. Paul's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Seaforths.jpeg",
        "lat": "",
        "long": "",
        "name": "Seaforths",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Smith (Darby).jpeg",
        "lat": "",
        "long": "",
        "name": "Smith (Darby)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Rigby (Perrys).jpeg",
        "lat": "",
        "long": "",
        "name": "Rigby (Perrys)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Gree Castle.jpeg",
        "lat": "",
        "long": "",
        "name": "Gree Castle",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Monteros.jpeg",
        "lat": "",
        "long": "",
        "name": "Monteros",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Ne Division (Tremills).jpeg",
        "lat": "",
        "long": "",
        "name": "Ne Division (Tremills)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Hermitage.jpeg",
        "lat": "",
        "long": "",
        "name": "Hermitage",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Joll Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Joll Hill",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Blubbe Valley (Rose Valley).jpeg",
        "lat": "",
        "long": "",
        "name": "Blubbe Valley (Rose Valley)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tranquil Vale.jpeg",
        "lat": "",
        "long": "",
        "name": "Tranquil Vale",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tottenham Park.jpeg",
        "lat": "",
        "long": "",
        "name": "Tottenham Park",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Willocks.jpeg",
        "lat": "",
        "long": "",
        "name": "Willocks",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Ffry (Frys).jpeg",
        "lat": "",
        "long": "",
        "name": "Ffry (Frys)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Orang Valley (Furlongs).jpeg",
        "lat": "",
        "long": "",
        "name": "Orang Valley (Furlongs)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Picart (Herman Vale).jpeg",
        "lat": "",
        "long": "",
        "name": "Picart (Herman Vale)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Sawcolts.jpeg",
        "lat": "",
        "long": "",
        "name": "Sawcolts",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Sag Hill (Tom Moores Mill  Upper).jpeg",
        "lat": "",
        "long": "",
        "name": "Sag Hill (Tom Moores Mill  Upper)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Mil Hill.jpeg",
        "lat": "",
        "long": "",
        "name": "Mil Hill",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Claremon (see #178).jpeg",
        "lat": "",
        "long": "",
        "name": "Claremon (see #178)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Tremontain  The Mountain.jpeg",
        "lat": "",
        "long": "",
        "name": "Tremontain  The Mountain",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Youngs.jpeg",
        "lat": "",
        "long": "",
        "name": "Youngs",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Young  Nantons.jpeg",
        "lat": "",
        "long": "",
        "name": "Young  Nantons",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Brook (Old Road).jpeg",
        "lat": "",
        "long": "",
        "name": "Brook (Old Road)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Morris (Old Mill  Brambles).jpeg",
        "lat": "",
        "long": "",
        "name": "Morris (Old Mill  Brambles)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Douglas Estate (Ravenscroft).jpeg",
        "lat": "",
        "long": "",
        "name": "Douglas Estate (Ravenscroft)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Yorke (Musketo Cove & Bear Gardens).jpeg",
        "lat": "",
        "long": "",
        "name": "Yorke (Musketo Cove & Bear Gardens)",
        "parish": "St. Mary's"
    },
    {
        "additional_info": "",
        "chronology": {},
        "date_of_establishment": "",
        "display_name": "",
        "enslaved_peoples": "",
        "extant_or_ruin": "",
        "image": "Mill_Files/Photos/Christia Valley  Biffins.jpeg",
        "lat": "",
        "long": "",
        "name": "Christia Valley  Biffins",
        "parish": "St. Mary's"
    }
]